import gulp from 'gulp';

// @group POSTCSS MODULES
import postcss from 'gulp-postcss';
import reporter from 'postcss-reporter';
import stylelint from 'stylelint';
import immutable from 'immutable-css';
import selector from 'postcss-custom-selectors';
import lost from 'lost';

// @group GULP MODULES
import plumber from 'gulp-plumber';
import sourcemaps from 'gulp-sourcemaps';
import nodemon from 'gulp-nodemon';
import eslint from 'gulp-eslint';
import sass from 'gulp-sass';
import babel from "gulp-babel";
import cache from 'gulp-cached';
import rename from 'gulp-rename';
import uglify from 'gulp-uglify';
import imagemin from 'gulp-imagemin';
import mocha from 'gulp-mocha';
import shell from 'gulp-shell';
import pug from 'gulp-pug';
import gulppuglint from 'gulp-pug-lint';
import changed from 'gulp-changed';

// @group UTILITY
import rimraf from 'rimraf';
import browserSync from 'browser-sync';
const reload = browserSync.reload;
import source from 'vinyl-source-stream';
import buffer from 'vinyl-buffer';
import browserify from 'browserify';
import watchify from 'watchify';
import transform from 'vinyl-transform';
import babelify from 'babelify';

// Monitoring configuration
import firebase from 'firebase-tools';
import packageJson from './package.json';
import moment from 'moment';
import jsonfile from 'jsonfile';
import puglint from 'pug-lint';
import childProcess from 'child_process';
import os from 'os';

let nbrErrorJade;
let nbrErrorJS;
let nbrErrorCSS;
let nbrWarningJS;

// ########################################

const project = {
  app: require('./bower.json').appPath || 'app',
  dist: 'build',
  tmp: '.tmp'
};

const paths = {
  'server': {
    LOCAL: 'http://localhost:3000'
  },
  fonts: {
    ALL: './app/fonts/**',
    DEST: './build/resources/css/fonts/'
  },
  styles: {
    SRC: './app/styles/styles.scss',
    ALL: [
      './app/styles/**/*.scss',
      './app/views/**/*.scss'
      ],
    DEST: './build/resources/css/'
  },
  scripts: {
    BOWER: './bower.json',
    SRC: './app/scripts/script.js',
    ALL: [
      './app/scripts/**/*.js',
      './test/*.js',
      './app/views/**/*.js',
      './server.js',
      './gulpfile.babel.js',
      '!node_modules/**'
    ],
    DEST: './build/resources/js',
    TEST: './test/*.js'
  },
  icon: {
    ALL: 'images/icons/*.svg',
    TEMPLATE: 'styles/template/icons.scss',
    GENERATED_CSS: './autogenerated/icon.scss',
    AUTO_GENERATED_CSS: './public/fonts/Icons/autogenerated/icon.scss',
    STYLE_BASE: 'styles/base',
    DEST: './build/resources/fonts/icons/'
  },
  images: {
    SRC: './app/images/**/*.{jpg,jpeg,png}',
    DEST: './build/resources/images/'
  },
  pug: {
    ALL: './app/views/**',
    MAIN: [
      './app/views/**/*.pug',
      '!./app/views/**/_*.pug',
      '!./app/views/_*/**/*.pug',
      '!./app/views/**/**/_*/*.pug'
    ],
    DEST: './build/'
  },
  critical:{
    CSS: './app/views/criticals/css/default.css',
    JS: './app/views/criticals/js/default.js'
  }
};

// ########################################

export function lintPugTask (done) {
  return gulp.src(paths.pug.MAIN)
    .pipe(plumber((error) => {
      console.log(error);
      this.emit('end');
    }))
    .pipe(gulppuglint())
    .pipe(reload({ stream: true }))
    .on('end', () => {
      done();
    });
}

export function htmlTask (done) {
  return gulp.src(paths.pug.MAIN)
    .pipe(plumber((error) => {
      console.log(error);
      this.emit('end');
    }))
    .pipe(pug({
      pretty: true
    }))
    .pipe(gulp.dest(paths.pug.DEST))
    .on('end', () => {
      done();
    });
}

// ########################################

export function lintStylesTask (done) {
  return gulp.src(paths.styles.ALL)
    .pipe(plumber((error) => {
      console.log(error);
      this.emit('end');
    }))
    .pipe(cache('css'))
    .pipe(postcss([
      stylelint(),
      reporter({
        clearMessages: true
      })
    ],{ parser: require('postcss-scss') }))
    .on('end', () => {
      done();
    });
}

export function stylesTask (done) {
  const processors = [
    require('postcss-normalize'), // [2]
    require('cssnano')({
      autoprefixer: false, // [1]
      discardComments: { removeAll: true }
    }),
    require('postcss-cssnext')({
      browsers: ['> 5%', 'ie >= 10', 'Firefox < 20', 'ios 6', 'android 4']
    })
  ];
  return gulp.src(paths.styles.SRC)
    .pipe(plumber((error) => {
      console.log(error);
      this.emit('end');
    }))
    .pipe(sourcemaps.init())
      .pipe(sass())
      .pipe(postcss(processors))
      .pipe(rename({
        suffix: '.min'
      }))
    .pipe(sourcemaps.write('.'))
    // .pipe(sourcemaps.write('.', {includeContent: false})) To test -> performance
    .pipe(gulp.dest(paths.styles.DEST))
    .pipe(reload({ stream: true }))
    .on('end', () => {
      done();
    });
}

// ########################################

export function imagesTask () {
  return gulp.src(paths.images.SRC, { since: gulp.lastRun(imagesTask) })
    .pipe(plumber((error) => {
      console.log(error);
      this.emit('end');
    }))
    .pipe(changed(paths.images.DEST))
    .pipe(imagemin({
      progressive: true,
      interlaced: true,
      optimizationLevel: 5
    }))
    .pipe(gulp.dest(paths.images.DEST))
    .pipe(reload({ stream: true }));
}

// ########################################


export function javaScriptTask() {

  watchify.args.debug = true;

  var bundler;

  const getBundler = () => {
    if (!bundler) {
      bundler = watchify(browserify(paths.scripts.SRC, watchify.args));
    }
    return bundler;
  };

  const rebundle = () => {
    return getBundler()
      .transform(babelify)
      .bundle()
      .on('error', function(err) { console.log('Error: ' + err.message); })
      .pipe(source('script.js'))
      .pipe(buffer())
      .pipe(sourcemaps.init())
        .pipe(uglify())
        .pipe(rename({
          suffix: '.min'
        }))
      .pipe(sourcemaps.write('.'))
      .pipe(gulp.dest(paths.scripts.DEST))
      .pipe(reload({ stream: true }));
  }

  getBundler().on('update', rebundle);

  return rebundle();

}

/** ESlint */
export function lintJavaScript (done) {
  return gulp.src(paths.scripts.ALL)
    .pipe(plumber((error) => {
      console.log(error);
      this.emit('end');
    }))
    .pipe(cache('scripts'))
    .pipe(eslint({
      useEslintrc: true,
      configFile: './.eslintrc'
    }))
    .pipe(eslint.formatEach())
    .on('end', () => {
      done();
    });
}

export function testTask (done) {
  return gulp.src(paths.scripts.TEST, {
    read: false
  })
  .pipe(mocha()).on('error', done)
  .on('end', () => {
    done();
  });
}

// ########################################

export function copyFonts () {
  return gulp.src(paths.fonts.ALL)
    .pipe(gulp.dest(paths.fonts.DEST));
}

export function cleanBuild (cb) {
  rimraf('./build', cb);
}

// ########################################

export function serverTask (cb) {
	let started = false;

  return nodemon({
    script: './server.js',
    ext: 'js',
    watch: [
      'gulpfile.babel.js',
      'server.js'
    ],
    ignore: [
      './node_modules/',
      './bower_components',
      './build/resources/**/*'
    ],
    env: {
      'NODE_ENV': 'development',
      'DEBUG': 'appname:*'
    }
  })
  .on('start', function () {
    if (!started) {
      cb();
      started = true;
    }
  })
  .on('crash', () => {
    console.log('nodemon.crash');
  })
  .on('restart', () => {
    console.log('nodemon.restart');
  })
  .once('quit', () => {
    // handle ctrl+c without a big weep
    process.exit();
  });
}

// ########################################

export function browserTask () {
  browserSync.init(null, {
    proxy: paths.server.LOCAL,
    port: 3002,
    open: true,
    logFileChanges: true,
    logConnections: false,
    injectChanges: true,
    timestamps: false,
    ghostMode: {
      clicks: true,
      forms: true,
      scroll: false
    }
  });
}

// ########################################

export function monitoring (callback) {
  // Empty jsonfile

  const idComputer = os.hostname();
  const nameProject = packageJson.name;
  const firebaseToken = '1/NEpgg17d3mIGjrlH2iruYX8t2Jkm5qH0hN-eg8DbWWM';
  const firebaseData = './firebase-data.json';

  const currentTime = moment().format();

  // Ask prompt if idComputer is different and ask if good projectName

  stylelint.lint({
    files: paths.styles.SRC,
  })
  .then((data) => {
    const dataOutput = data.output;
    const dataFormat = dataOutput.match(/\{[^]*\}/gm);
    const errorCSS = JSON.parse(dataFormat);

    nbrErrorCSS = errorCSS.warnings.length;
  })
  .then(() => {
    // In progress
    const CLIpug = require('pug-lint');

    const cli = new CLIpug({
      _basePath: '.'
    });
  })
  .then(() => {
    const CLIEngine = require('eslint').CLIEngine;
    const cli = new CLIEngine({
      useEslintrc: true,
      configFile: './.eslintrc',
    });
    const report = cli.executeOnFiles(paths.scripts.ALL);

    nbrErrorJS = report.errorCount;
    nbrWarningJS = report.warningCount;
  })
  .then(() => {
    const nbrErrorJade = 'undefined';

    const obj = {
      'computerId': idComputer,
      'nbrErrors': {
        'errorCss': nbrErrorCSS,
        'errorJade': nbrErrorJade,
        'warningJs': nbrWarningJS,
        'errorJs': nbrErrorJS
      },
      'currentTime': currentTime
    };

    jsonfile.writeFile(firebaseData, obj, { spaces: 2 }, (err) => {
      // console.error(err)
    });
  })
  .then(() => {
    // firebase login
    childProcess.exec('firebase database:push /' + nameProject + ' firebase-data.json', (error, stdout, stderr) => {
      // console.log(stdout);
    });
  })
  .catch((err) => {
    console.error(err.stack);
  });
}

// ########################################

export function watchTask (done) {
  gulp.watch(paths.fonts.ALL, gulp.parallel(copyFonts));
  gulp.watch(paths.styles.ALL, gulp.parallel(css));
  gulp.watch(paths.scripts.ALL, gulp.parallel(lintJavaScript, testTask));
  gulp.watch(paths.pug.ALL, gulp.parallel(lintPugTask));
  gulp.watch(paths.images.SRC, gulp.parallel(imagesTask));
  done();
}

// ########################################

// Clearing the whole CSS and JS files
cache.caches = {};

const lint = gulp.series(lintStylesTask, lintJavaScript);
export { lint };

const css = gulp.series(lintStylesTask, stylesTask);
export { css };

const js = gulp.series(lintJavaScript, javaScriptTask);
export { js };

// Global tasks
const serve = gulp.series(gulp.parallel(browserTask, serverTask, css, js, monitoring, watchTask), (done) => {
  done()
});
export { serve };

const build = gulp.series(gulp.parallel(cleanBuild, copyFonts, imagesTask, htmlTask, css, js, testTask, (done) => {
  done();
}));
export { build };

const check = gulp.series(gulp.parallel(lintPugTask, js, testTask, (done) => {
  done();
}));
export { check };

export default build;
